### ISSUE TITLE
Missed updation:  Migration to C++11 

### ISSUE THREAD

**Issue by vipint99** [sigsergv/nfc-tutorial#1]
Hi there,
I was just using this very useful utility  PCSC-tutorial . While trying to compile for  
 pcsc-tutorial/example-utils/cmd-get-data.cpp (Migration to C++11 )  , I noticed that code has not changed and we have not removed  old references to xpcsc:: CLA and  INS 

 Line: 88 :  xpcsc::Byte cmd[] = {xpcsc::CLA_PICC, xpcsc::INS_PICC_GET_DATA, 0x0, 0x0, 0x0}; 

Thanks
Vipin

**Comment by sigsergv** [comment]
Thank you!

Fixed in 312e46ef1d1e0046bf6fded20719cbd1b03161ec
